In [1]:
import tensorflow as tf

In [2]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\ProgramData\\Miniconda\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [3]:
#Data types in A Tensor

string = tf.Variable("This", tf.string)
number = tf.Variable(33, tf.int16)
flt = tf.Variable(3.5, tf.float64)

In [4]:
#Rank Of Tensors

rank1_tensor = tf.Variable(["test"], tf.string)
rank2_tensor = tf.Variable([["Hola","hi"],["ciao", "bye"]], tf.string)

In [5]:
print("Rank Of rank1_tensor: ", tf.rank(rank1_tensor))
print("Rank Of rank2_tensor: ", tf.rank(rank2_tensor))

Rank Of rank1_tensor:  tf.Tensor(1, shape=(), dtype=int32)
Rank Of rank2_tensor:  tf.Tensor(2, shape=(), dtype=int32)


In [6]:
rank2_tensor.shape

TensorShape([2, 2])

In [7]:
#changing shape of a tensor

tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor1, [3,-1])

In [8]:
print(tensor1)
print(tensor2, "\n")
print(tensor3, "\n")

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32) 

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32) 

